name: Deploy Backend

on:
  push:
    branches:
      - main   # или ветка, из которой деплоишь

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v3

      - name: Подключиться и выполнить деплой на сервере
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /root/ProTalk_backend   # укажи путь к проекту на сервере
            git pull origin main       # обновляем код
            docker-compose down        # останавливаем контейнеры (если используешь docker-compose)
            docker-compose up -d --build   # поднимаем контейнеры с билдом
            # или команды для перезапуска сервиса без Docker, например:
            # systemctl restart protalk-backend.service
