name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v3

      - name: Подключиться и выполнить деплой на сервере
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /root/ProTalk_backend
            git pull origin main

            # Останавливаем контейнеры, чтобы не было конфликтов
            docker-compose down

            # Собираем и запускаем контейнеры в фоне
            docker-compose up -d --build

            # Ждем, пока база станет здоровой (max 30 сек)
            echo "Waiting for DB to become healthy..."
            for i in {1..30}; do
              status=$(docker inspect --format='{{.State.Health.Status}}' protalk_backend_db_1)
              if [ "$status" = "healthy" ]; then
                echo "DB is healthy"
                break
              fi
              echo "Waiting for DB... ($i)"
              sleep 1
            done

            if [ "$status" != "healthy" ]; then
              echo "DB did not become healthy, aborting"
              exit 1
            fi

