name: SSH Test

on:
  workflow_dispatch:

jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка подключения по SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            echo "SSH подключение успешно!"
            uname -a
